---
name: 'Bug report'
about: 'File a bug report'
---

## Bug report

### Base UI version

e.g. v1.0.2

### Which browser are you using?

Chrome/Safari/Firefox/Safari iOS etc.

### Which OS are you using?

Mac OS/Windows/Other etc.

### Which assistive tech are you using (if applicable)?

Voiceover/JAWS etc.

### Current Behavior

Provide a clear and concise description of the current behaviour you're experiencing. If applicable, provide screenshots and/or videos.

### Expected behavior

Provide a clear and concise description of the expected behaviour.

### Reproducible example

Link to a CodeSandbox, StackBlitz, or other IDE.

### Additional context

Provide any additional context that might help us identify the problem and find a solution.
